name: CI
  
on:

  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connection_Checkstyle
        uses: actions/checkout@v3
        
      - name: Build
        run: gradle clean build 
        
      - name: Save_Artifact
        uses: actions/upload-artifact@v3
        with:
          name: testReport
          path: build/jacoco/test.exec 
      
  checkstyle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Connection_Checkstyle
        uses: actions/checkout@v3


  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Connection_Checkstyle
        uses: actions/checkout@v3



